# Generated by Django 3.2.9 on 2021-11-27 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='email_id',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='contact_number',
        ),
    ]
